# generate Go code from list of codes
for line in open('codes.txt'):
    s = line.strip()

    if s == "":
        continue

    if s.startswith('Response code'):
        code = s.split()[2]
        
    if s.startswith('Generated by: '):
        generated_by = s.replace('Generated by: ', '')

    if s.startswith('Meaning: '):
        meaning = s.replace('Meaning: ', '')
        print(f"\"{code}\": ResponseCodeMeaning{{ GeneratedBy: \"{generated_by}\", Meaning: \"{meaning}\" }},")
